### ISSUE TITLE
File name too long when invoke ConvertCommand

### ISSUE THREAD

**Issue by qwazer** [md2conf/md2conf#212]
java.lang.RuntimeException: java.nio.file.FileSystemException: /docs/xxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.md: File name too long
        at io.github.md2conf.converter.view2md.View2MdConverter.convert(View2MdConverter.java:59)
        at io.github.md2conf.toolset.ConvertCommand.convert(ConvertCommand.java:66)
        at io.github.md2conf.toolset.DumpconCommand.dumpcon(DumpconCommand.java:36)

**Comment by qwazer** [comment]
fixed in #213
